# Generated by Django 4.2.10 on 2024-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='img1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='img2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='img3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='img4',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='studio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(default='', max_length=250),
        ),
    ]
