# Generated by Django 4.2.10 on 2024-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_users_game_code_alter_game_img1_alter_game_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=''),
        ),
    ]
