# Generated by Django 4.2.10 on 2024-03-01 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
