# Generated by Django 4.2.10 on 2024-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('studio', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=50)),
            ],
        ),
    ]
